spring:
  application:
    name: inventory-management
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:invMan
    driver-class-name: org.h2.Driver
    username: sa
    password: abc123